version: 0.0 
os: linux 
files: 
  - source: /
    destination: /DEV/devops/BE/codedeploy
hooks: 
  ApplicationStop: 
    - location: devops/scripts/stop_be_node.sh
      timeout: 300 
      runas: root
  BeforeInstall: 
    - location: devops/scripts/prepare_be.sh
      timeout: 300
      runas: root
  Install: 
    - location: devops/scripts/install_nodemodules.sh
      timeout: 300
      runas: root 	  
  AfterInstall: 
    - location: devops/scripts/after_install.sh
      timeout: 300
      runas: root 
  ApplicationStart: 
    - location: devops/scripts/start_node.sh
      timeout: 300 
      runas: root