version: 0.2
env:
    variables:
        BUILD_ENV: "DEV"
phases:
    install:
        commands:
            - echo move appspec to root path...
            - mv devops/appspec.yml .
    build:
        commands:
            - echo Build started
    post_build:
         commands:
            - echo Build Completed
artifacts:
  files:
    - 'backend_service/**/*'
    - 'devops/**/*'
    - 'appspec.yml'