export default {
    modifySocialProfileAndStatusUpdate:'insert into candidate_social(candidate_id, github, github_link, linkedin, linkedin_link, stackoverflow, stackoverflow_link,status, created_by, updated_by, created_on, updated_on) values($1,$2,$3,$4,$5,$6,$7,true,$8,$8,$9,$9) on conflict(candidate_id) do update set github=$2, github_link=$3, linkedin=$4, linkedin_link=$5, stackoverflow=$6,stackoverflow_link=$7,status=true,updated_by=$8,updated_on=$9;',
    addDefaultAssessmentTraits: 'insert into candidate_assesement (candidate_id, assesement_name, assesment_type, stage_name, created_on, updated_on, created_by, updated_by, stage_start_date) values ($candidateid, unnest(array(select r.assessment_name from review_steps r where status = true)), unnest(array(select r.review_type from review_steps r where status = true)), unnest(array(select r.stage_name from review_steps r where status = true)), $currenttime,$currenttime,$employeeid,$employeeid,$currenttime)',
    listFreelancerJobs:'select p.position_id, position_name, developer_count, job_description, experience_level, jc.job_category_id,jc.job_category_name, array_agg (skill_name) as skills from positions p left join job_category jc on jc.job_category_id = p.job_category_id left join job_skills js on p.position_id = js.position_id and js.top_rated_skill=true and js.status=true left join skills s on js.skill_id = s.skill_id where p.status = true and p.job_status = 6 and p.position_name ilike $search group by p.position_id,jc.job_category_id ',
    getellowAdmins:"select concat(firstname,' ',lastname) as name ,employee_id as employeeId from employee where status=true and user_role_id=1",
    getFreelancerCompanyId:'select company_id from company where company_name like $freelancer',
    updateCandidateStatus:'UPDATE candidate SET candidate_status=$4,updated_by=$2,updated_on=$3 WHERE candidate_id=$1 returning candidate_first_name,candidate_last_name',
    getPositionsDetails:'select p.position_id, p.position_name, p.developer_count, p.job_description, p.experience_level, jc.job_category_id,jc.job_category_name, array_agg (skill_name) as skills from positions p left join candidate_position cp on cp.position_id=p.position_id left join job_category jc on jc.job_category_id = p.job_category_id left join job_skills js on p.position_id = js.position_id and js.top_rated_skill=true and js.status=true left join skills s on js.skill_id = s.skill_id where cp.candidate_id=$1 and p.status = true and p.job_status = 6 group by p.position_id,jc.job_category_id ',
    getImageNames:'select image,candidate_first_name,candidate_last_name,email_address from candidate where candidate_id=$1'
}