// ---------------------------Email path constants-------------------------------------------------//

export const emailPath = {
  ADD_RESOURCE_HIRER: 'src/emailTemplates/addCandidateHirerMail.html',
  ADD_RESOURCE: 'src/emailTemplates/addCandidatesText.html',
  ADD_RESOURCE_USER: 'src/emailTemplates/addCandidatesUsersText.html',
  BLACKLIST_RESOURCE: 'src/emailTemplates/addToBlacklistMail.html',
  DISCUSSION_WITH_RESOURCE: 'src/emailTemplates/assigneeDisscussionMailText.html',
  DELETE_RESOURCE_FROM_POSITION: 'src/emailTemplates/candidateDeletionMailText.html',
  ELLOW_SCREENING_CHANGE_ASSIGNEE: 'src/emailTemplates/changeAssigneeText.html',
  CLIENT_SCREENING_CHANGE_ASSIGNEE: 'src/emailTemplates/clientScreeningAssigneeText.html',
  CLIENT_SCREENING_REJECTION: 'src/emailTemplates/ellowRejectionAssigneeMailText.html',
  RESOURCE_CLIENT_SCREENING_REJECTION: 'src/emailTemplates/ellowRejectionResourceMailText.html',
  ELLOW_VETTED: 'src/emailTemplates/ellowVettedText.html',
  REFERRAL_WELCOME_MAIL: 'src/emailTemplates/referalWelcomeMail.html',
  TEST_LINK_NOTIFIACTION: 'src/emailTemplates/ellowTestLinkNotification.html',
  REFERRAL_THANKS_MAIL: 'src/emailTemplates/referalThanksMail.html',
  FREELANCER_SUBMITTED: 'src/emailTemplates/freelancerSubmitText.html',
  INTERVIEW_REQUESTED: 'src/emailTemplates/interviewRequestMailText.html',
  MAKE_OFFER: 'src/emailTemplates/makeOfferMailText.html',
  NEW_USER_ADMIN: 'src/emailTemplates/newUserAdminText.html',
  ELLOW_SCREENING_DISCUSSION: 'src/emailTemplates/recruitersDiscussionMailText.html',
  CLIENT_SCREENING_REJECT: 'src/emailTemplates/rejectionMailText.html',
  UNBLACKLIST_RESOURCE: 'src/emailTemplates/removeFromBlacklistMail.html',
  CLIENT_SCREENING_ACEEPTED_OFFER: 'src/emailTemplates/resourceAcceptionAssigneeMailText.html',
  RESOURCE_DISCUSSION: 'src/emailTemplates/resourceDiscussionMailText.html',
  RESOURCE_REJECTED_OFFER: 'src/emailTemplates/resourceRejectionMailText.html',
  RESUME_SHARE_LINK: 'src/emailTemplates/resumeShareText.html',
  RESOURCE_SELECTED: 'src/emailTemplates/selectionMailText.html',
  RESUME_SHARE_PDF: 'src/emailTemplates/sharePdfText.html',
};
