#!/bin/bash
pwd

NODE_HOME=/DEV/devops/BE/codedeploy/node
cd $NODE_HOME/backend_service/auth && ls -l
cd $NODE_HOME/backend_service/company && ls -l
cd $NODE_HOME/backend_service/employee && ls -l
cd $NODE_HOME/backend_service/jobs && ls -l
cd $NODE_HOME/backend_service/settings && ls -l
cd $NODE_HOME/backend_service/candidate && ls -l
