#!/bin/bash
pwd

NODE_HOME=/DEV/devops/BE/codedeploy/node
cd $NODE_HOME/backend_service/auth && npm insatll                   
cd $NODE_HOME/backend_service/company && npm insatll                   
cd $NODE_HOME/backend_service/employee && npm insatll                   
cd $NODE_HOME/backend_service/jobs && npm insatll                   
cd $NODE_HOME/backend_service/settings && npm insatll                   
cd $NODE_HOME/backend_service/candidate && npm insatll
