#!/bin/bash
pwd
0=auth
1=company
2=employee
3=jobs
4=settings
5=candidate
NODE_HOME=/DEV/devops/BE/codedeploy
cd $NODE_HOME/backend_service/$0 && npm insatll                   
cd $NODE_HOME/backend_service/$1 && npm insatll                   
cd $NODE_HOME/backend_service/$2 && npm insatll                   
cd $NODE_HOME/backend_service/$3 && npm insatll                   
cd $NODE_HOME/backend_service/$4 && npm insatll                   
cd $NODE_HOME/backend_service/$5 && npm insatll
