#!/bin/bash
pwd
NODE_HOME=/DEV/devops/BE/codedeploy/stagelocation
cd $NODE_HOME/backend_service/auth && npm run prod && npm run prod && npm run prod && sleep 10 
cd $NODE_HOME/backend_service/company && npm run prod && npm run prod && npm run prod && sleep 10 
cd $NODE_HOME/backend_service/employee && npm run prod && npm run prod && npm run prod && sleep 10 
cd $NODE_HOME/backend_service/jobs && npm run prod && npm run prod && npm run prod && sleep 10 
cd $NODE_HOME/backend_service/settings && npm run prod && npm run prod && npm run prod && sleep 10 
cd $NODE_HOME/backend_service/candidate && npm run prod && npm run prod && npm run prod && sleep 10 
netstat -nlpt |grep :400[0-5]
pm2 status
pm2 logs