export default {
    //getAllJobReceived: 'select jr.job_received_id, jr.position_id, p.company_id, c.company_name as company_name, p.position_name, p.location_name, jr.created_on, case when cj.company_job_status>0 then company_job_status else jr.job_received_status end jobreceivedstatus from job_received jr inner join positions p on  p.position_id =jr.position_id inner join  company c on c.company_id = p.company_id left outer join company_job cj  on cj.job_received_id = jr.job_received_id where jr.status = true',
    getAllJobReceived:'select jr.job_received_id, jr.position_id, p.company_id, c.company_name as company_name, p.position_name, p.location_name, jr.created_on, jr.job_received_status from job_received jr inner join positions p on  p.position_id =jr.position_id inner join  company c on c.company_id = p.company_id  where jr.status = true',
    getJobReceivedById: 'select P.position_id, P.company_id, C.company_name as company_name, P.position_name, P.job_description, P.developer_count, experience_level, currency_type_id, min_budget, max_budget, JS.skill_id, S.skill_name , P.location_name, P.created_on, P.job_status, cj.is_flag from job_received jr inner join positions p on  p.position_id =jr.position_id  inner join  company c on c.company_id = p.company_id left outer join company_job cj on cj.job_received_id = jr.job_received_id LEFT OUTER JOIN job_skills JS ON JS.position_id = P.position_id LEFT OUTER JOIN skills S ON S.skill_id = JS.skill_id where jr.status = true and jr.job_received_id =$1 and cj.company_id =$2',
    updateFlag: 'INSERT INTO company_job (job_received_id, company_id, is_flag ,created_by, created_on, status ) VALUES ($1, $2, $3, $4, $5, true) ON CONFLICT (job_received_id, company_id) DO UPDATE SET is_flag = EXCLUDED.is_flag,updated_by=$4, updated_on = $5',
    updateReject: 'INSERT INTO company_job (job_received_id, company_id, company_job_status ,created_by, created_on, status ) VALUES ($1, $2, $3, $4, $5, true) ON CONFLICT (job_received_id, company_id) DO UPDATE SET company_job_status = 2, updated_on = $4',
    getProfile: "SELECT * FROM candidate WHERE company_id=$1",
    addProfile: 'INSERT INTO candidate (candidate_name, company_id, job_received_id, cover_note, rate, candidate_status) VALUES %L',
    updateDeveloperCount: 'update  positions p set developer_count = developer_count - $1, updated_on = $2 from job_received jr where jr.position_id  = p.position_id  and job_received_id = $3',
}